# Generated by Django 3.2.25 on 2024-05-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240515_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
