# Generated by Django 3.2.25 on 2024-05-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='imageURL',
            field=models.CharField(max_length=80),
        ),
    ]
